### ISSUE TITLE
Set functions unit tests

### ISSUE THREAD

**Issue by sajanrajdev** [Citadel-DAO/staked-citadel-locker#8]
Test all of the set functions for different scenarios, example:
- [x]  setStakingContract
- [x]  setStakeLimits
- [x]  setKickIncentive
- [x]  notifyRewardAmount
- [x] setBoost

**Comment by Fatimanaz** [comment]
notifyRewardAmount is already tested here - https://github.com/Citadel-DAO/citadel-contracts/pull/152

**Comment by sajanrajdev** [comment]
Tackled through: https://github.com/Citadel-DAO/staked-citadel-locker/pull/9/files
